name = "uniq-do"
route = { pattern = "uniq.do/*", zone_name = "uniq.do" }
main = "dist/index.mjs"
compatibility_date = "2022-08-25"

[build]
command = "npm run build"

[build.upload]
format = "modules"

services = [
]
